name: Setup Static WordPress for Vercel or GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PHP_VERSION: '8.2'

jobs:
  setup-wordpress:
    name: Setup and Deploy Static WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, mysqli, gd, xml, zip
          tools: composer:v2

      - name: Create composer.json
        run: |
          cat > composer.json << 'EOL'
          {
            "require": {
              "wp-cli/wp-cli-bundle": "^2.8",
              "vlucas/phpdotenv": "^5.6"
            }
          }
          EOL

      - name: Install PHP Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Setup WordPress
        run: |
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          mv wordpress/* .
          rm -rf wordpress latest.tar.gz
          mkdir -p wp-content/uploads

      - name: Configure WordPress
        run: |
          wp config create --dbname=example --dbuser=example --dbpass=example --dbhost=example
          wp core install --url="http://localhost" --title="Static WordPress" --admin_user="admin" --admin_password="admin" --admin_email="admin@example.com"

      - name: Install WP2Static Plugin
        run: wp plugin install wp2static --activate

      - name: Generate Static Files
        run: |
          wp plugin activate wp2static
          wp wp2static generate
          cp -R wp-content/uploads/wp2static-processed ./public

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel deploy --prod --token $VERCEL_TOKEN

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
